-- RETIRED: historical free-quota + paid AI credit model.
--
-- Do not run this file on the current MedSlime schema.
-- The previous version mixed a daily free allowance with a purchasable stored
-- AI-credit balance. That commercial model has been removed.
--
-- Active setup:
--   supabase/payment_entitlement_v2.sql
--
-- Current rule:
--   * Free accounts may use up to 5 detailed explanations per Taiwan calendar day.
--   * Daily uses reset and unused uses do not carry over.
--   * There is no paid AI-credit fallback after the daily limit is reached.
--   * AI usage counts cannot be purchased, topped up, transferred, or stored.
--   * A purchased national-exam explanation entitlement grants permanent access
--     only to that identified exam.
--
-- payment_entitlement_v2.sql owns the active consume_ai_detail_daily_use() and
-- refund_ai_detail_daily_use() RPCs and drops the historical credit-named RPCs.
