-- RETIRED: historical AI credit consumption model.
--
-- Do not run this file on the current MedSlime schema.
-- The old implementation created stored AI-credit RPCs such as
-- consume_ai_detail_credit() / refund_ai_detail_credit(), which are no longer
-- part of the product or payment model.
--
-- Active setup:
--   supabase/payment_entitlement_v2.sql
--
-- Current rule:
--   * Free accounts may use up to 5 detailed explanations per Taiwan calendar day.
--   * Daily uses reset and never accumulate.
--   * AI uses cannot be purchased, topped up, transferred, or stored.
--   * A purchased national-exam explanation entitlement bypasses the daily limit
--     only for that specifically purchased exam.
--
-- payment_entitlement_v2.sql drops the historical credit-named RPCs. Keep this
-- file only as a compatibility note so an old migration cannot recreate them.
