-- RETIRED: MedSlime 2.0 no longer uses the historical AI-credit payment model.
--
-- Do not run the old ECPay bootstrap that created grant_type = 'ai_detail' and
-- ai_detail_credits fulfillment. That model represented stored consumable value
-- and has been replaced by direct service/content entitlements.
--
-- Active setup / migration:
--   supabase/payment_entitlement_v2.sql
--
-- Current paid outcomes are only:
--   1. MedSlime Pro 30-day fixed access
--   2. Permanent access to one specifically identified national-exam explanation set
--
-- Gameplay coins, tickets, gacha resources and AI usage counts are not purchasable.
