-- RETIRED: do not run this file.
--
-- The first 14-day trial migration granted Pro to every existing account and
-- left the signup trigger open indefinitely. That behavior was intentionally
-- replaced by `signup_campaign_trial_and_welcome_gift.sql`.
--
-- Current campaign rule:
--   * signup window: 2026-09-12 00:00 <= created_at < 2026-09-26 00:00 Asia/Taipei
--   * eligible signup receives one 14-day Pro trial from signup time
--   * accounts outside the window receive no trial
--   * eligible signup may claim one 10-ticket welcome gift
--   * detailed AI explanations still keep the existing hard daily free limit
--
-- Keep this retired file only as migration history. Running it again would
-- recreate the broad grant that the replacement migration explicitly removed.
