-- RETIRED COMPATIBILITY NOTE
--
-- Real-money coin purchases were removed earlier in MedSlime 2.0. The old
-- version of this script still recreated AI-credit fulfillment, so it must not
-- be run on the current schema.
--
-- Use instead:
--   supabase/payment_entitlement_v2.sql
--
-- Current payment rule:
--   Payment -> fixed 30-day Pro access
--   Payment -> permanent access to one identified national-exam explanation set
--
-- No payment may grant coins, tickets, gacha pulls, fragments, accessories,
-- AI credits, wallet balance or another prepaid consumable value.
