-- RETIRED COMPATIBILITY NOTE
--
-- The stored-value AI credit model has been fully superseded by Payment
-- Entitlement 2.0. Do not run the historical version of this script because it
-- recreated credit-named RPCs.
--
-- Active migration:
--   supabase/payment_entitlement_v2.sql
--
-- Current AI rule:
--   * Free accounts: up to 5 detailed-explanation views per Taiwan calendar day
--   * Daily uses reset and never accumulate
--   * AI uses cannot be purchased, topped up, transferred or stored
--   * A purchased national-exam explanation set bypasses the daily limit only
--     for that specifically identified exam
